// i18n.js — Smart Serve · 11 Indian Languages

const LANGUAGES = [
  { code: 'en', label: 'English',   nativeLabel: 'English',   voice: 'en-IN'  },
  { code: 'hi', label: 'Hindi',     nativeLabel: 'हिन्दी',    voice: 'hi-IN'  },
  { code: 'pa', label: 'Punjabi',   nativeLabel: 'ਪੰਜਾਬੀ',   voice: 'pa-IN'  },
  { code: 'ta', label: 'Tamil',     nativeLabel: 'தமிழ்',     voice: 'ta-IN'  },
  { code: 'te', label: 'Telugu',    nativeLabel: 'తెలుగు',    voice: 'te-IN'  },
  { code: 'kn', label: 'Kannada',   nativeLabel: 'ಕನ್ನಡ',    voice: 'kn-IN'  },
  { code: 'ml', label: 'Malayalam', nativeLabel: 'മലയാളം',   voice: 'ml-IN'  },
  { code: 'mr', label: 'Marathi',   nativeLabel: 'मराठी',     voice: 'mr-IN'  },
  { code: 'gu', label: 'Gujarati',  nativeLabel: 'ગુજરાતી',  voice: 'gu-IN'  },
  { code: 'bn', label: 'Bengali',   nativeLabel: 'বাংলা',     voice: 'bn-IN'  },
  { code: 'or', label: 'Odia',      nativeLabel: 'ଓଡ଼ିଆ',    voice: 'or-IN'  },
];

const TRANSLATIONS = {
  en: {
    appTitle: 'Smart Serve',
    appSub: 'Home Inventory',
    inventory: 'Inventory',
    shoppingList: 'Shopping',
    addItemPlaceholder: 'Type item name...',
    qtyLabel: 'Qty',
    inventoryEmpty: 'No items yet. Add your first item above!',
    shoppingEmpty: 'All stocked up! Nothing to buy.',
    selectLanguage: 'Choose Language',
    shareWhatsApp: 'Share via WhatsApp',
    clearAll: 'Clear All',
    restock: 'Restock',
    inStock: 'In Stock',
    lowStock: 'Running Low',
    outOfStock: 'Out of Stock',
    needToBuy: 'Need to buy',
    toastAdded: '✓ Item added',
    toastRemoved: '✓ Item removed',
    toastRestocked: '✓ Restocked!',
    toastCleared: '✓ List cleared',
    toastAutoCart: '🛒 Added to shopping list',
    scanBtn: 'Scan',
    voiceBtn: 'Voice',
    scanTitle: 'Scan Product',
    scanSub: 'Point camera at item or barcode',
    scanClose: 'Close',
    scanDetecting: 'Detecting...',
    scanFound: 'Found: ',
    addToInventory: 'Add to Inventory',
    scanManualPlaceholder: 'Or type name here...',
    sortBy: 'Sort',
    sortName: 'Name',
    sortQty: 'Quantity',
    sortStatus: 'Status',
    searchPlaceholder: 'Search items...',
    statsTotal: 'Total Items',
    statsLow: 'Low Stock',
    statsOut: 'Need to Buy',
    minQtyLabel: 'Min Qty',
    editItem: 'Edit',
    saveEdit: 'Save',
    cancel: 'Cancel',
  },
  hi: {
    appTitle: 'स्मार्ट सर्व',
    appSub: 'घर का सामान',
    inventory: 'सामान',
    shoppingList: 'खरीदारी',
    addItemPlaceholder: 'सामान का नाम लिखें...',
    qtyLabel: 'मात्रा',
    inventoryEmpty: 'कोई सामान नहीं। ऊपर जोड़ें!',
    shoppingEmpty: 'सब कुछ भरपूर है! कुछ नहीं खरीदना।',
    selectLanguage: 'भाषा चुनें',
    shareWhatsApp: 'WhatsApp पर भेजें',
    clearAll: 'सब हटाएं',
    restock: 'वापस लाएं',
    inStock: 'उपलब्ध',
    lowStock: 'कम है',
    outOfStock: 'खत्म',
    needToBuy: 'खरीदना है',
    toastAdded: '✓ जोड़ा गया',
    toastRemoved: '✓ हटाया गया',
    toastRestocked: '✓ वापस आया!',
    toastCleared: '✓ सूची साफ़',
    toastAutoCart: '🛒 खरीदारी सूची में जोड़ा',
    scanBtn: 'स्कैन',
    voiceBtn: 'आवाज़',
    scanTitle: 'सामान स्कैन करें',
    scanSub: 'कैमरा सामान या बारकोड पर लगाएं',
    scanClose: 'बंद करें',
    scanDetecting: 'पहचान रहा है...',
    scanFound: 'मिला: ',
    addToInventory: 'सूची में जोड़ें',
    scanManualPlaceholder: 'या यहाँ नाम लिखें...',
    sortBy: 'क्रम',
    sortName: 'नाम',
    sortQty: 'मात्रा',
    sortStatus: 'स्थिति',
    searchPlaceholder: 'खोजें...',
    statsTotal: 'कुल सामान',
    statsLow: 'कम स्टॉक',
    statsOut: 'खरीदना है',
    minQtyLabel: 'न्यूनतम',
    editItem: 'बदलें',
    saveEdit: 'सेव करें',
    cancel: 'रद्द करें',
  },
  pa: {
    appTitle: 'ਸਮਾਰਟ ਸਰਵ',
    appSub: 'ਘਰ ਦਾ ਸਾਮਾਨ',
    inventory: 'ਸਾਮਾਨ',
    shoppingList: 'ਖਰੀਦਾਰੀ',
    addItemPlaceholder: 'ਸਾਮਾਨ ਦਾ ਨਾਮ ਲਿਖੋ...',
    qtyLabel: 'ਮਾਤਰਾ',
    inventoryEmpty: 'ਕੋਈ ਸਾਮਾਨ ਨਹੀਂ। ਉੱਪਰ ਜੋੜੋ!',
    shoppingEmpty: 'ਸਭ ਕੁਝ ਭਰਿਆ ਹੈ!',
    selectLanguage: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    shareWhatsApp: 'WhatsApp ਤੇ ਭੇਜੋ',
    clearAll: 'ਸਭ ਹਟਾਓ',
    restock: 'ਵਾਪਸ ਲਿਆਓ',
    inStock: 'ਉਪਲਬਧ',
    lowStock: 'ਘੱਟ ਹੈ',
    outOfStock: 'ਖਤਮ',
    needToBuy: 'ਖਰੀਦਣਾ ਹੈ',
    toastAdded: '✓ ਜੋੜਿਆ ਗਿਆ',
    toastRemoved: '✓ ਹਟਾਇਆ ਗਿਆ',
    toastRestocked: '✓ ਵਾਪਸ ਆਇਆ!',
    toastCleared: '✓ ਸੂਚੀ ਸਾਫ਼',
    toastAutoCart: '🛒 ਖਰੀਦਾਰੀ ਸੂਚੀ ਵਿੱਚ ਜੋੜਿਆ',
    scanBtn: 'ਸਕੈਨ',
    voiceBtn: 'ਆਵਾਜ਼',
    scanTitle: 'ਸਾਮਾਨ ਸਕੈਨ ਕਰੋ',
    scanSub: 'ਕੈਮਰਾ ਸਾਮਾਨ ਜਾਂ ਬਾਰਕੋਡ ਤੇ ਲਗਾਓ',
    scanClose: 'ਬੰਦ ਕਰੋ',
    scanDetecting: 'ਪਛਾਣ ਰਿਹਾ ਹੈ...',
    scanFound: 'ਮਿਲਿਆ: ',
    addToInventory: 'ਸੂਚੀ ਵਿੱਚ ਜੋੜੋ',
    scanManualPlaceholder: 'ਜਾਂ ਇੱਥੇ ਨਾਮ ਲਿਖੋ...',
    sortBy: 'ਕ੍ਰਮ',
    sortName: 'ਨਾਮ',
    sortQty: 'ਮਾਤਰਾ',
    sortStatus: 'ਸਥਿਤੀ',
    searchPlaceholder: 'ਖੋਜੋ...',
    statsTotal: 'ਕੁੱਲ ਸਾਮਾਨ',
    statsLow: 'ਘੱਟ ਸਟਾਕ',
    statsOut: 'ਖਰੀਦਣਾ ਹੈ',
    minQtyLabel: 'ਘੱਟੋ ਘੱਟ',
    editItem: 'ਬਦਲੋ',
    saveEdit: 'ਸੇਵ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
  },
  ta: {
    appTitle: 'ஸ்மார்ட் சர்வ்',
    appSub: 'வீட்டு சரக்கு',
    inventory: 'கையிருப்பு',
    shoppingList: 'கொள்முதல்',
    addItemPlaceholder: 'பொருள் பெயர் உள்ளிடு...',
    qtyLabel: 'அளவு',
    inventoryEmpty: 'பொருட்கள் இல்லை. மேலே சேர்க்கவும்!',
    shoppingEmpty: 'எல்லாம் நிரம்பியது!',
    selectLanguage: 'மொழி தேர்ந்தெடு',
    shareWhatsApp: 'WhatsApp-ல் பகிர்',
    clearAll: 'அனைத்தும் அழி',
    restock: 'மீண்டும் சேர்',
    inStock: 'கையிருப்பு உள்ளது',
    lowStock: 'குறைவாக உள்ளது',
    outOfStock: 'தீர்ந்துவிட்டது',
    needToBuy: 'வாங்க வேண்டும்',
    toastAdded: '✓ சேர்க்கப்பட்டது',
    toastRemoved: '✓ நீக்கப்பட்டது',
    toastRestocked: '✓ மீண்டும் சேர்க்கப்பட்டது!',
    toastCleared: '✓ பட்டியல் அழிக்கப்பட்டது',
    toastAutoCart: '🛒 கொள்முதல் பட்டியலில் சேர்க்கப்பட்டது',
    scanBtn: 'ஸ்கேன்',
    voiceBtn: 'குரல்',
    scanTitle: 'பொருள் ஸ்கேன்',
    scanSub: 'கேமராவை பொருள் அல்லது பார்கோடில் நோக்கு',
    scanClose: 'மூடு',
    scanDetecting: 'கண்டறிகிறது...',
    scanFound: 'கண்டுபிடித்தது: ',
    addToInventory: 'சேர்க்கவும்',
    scanManualPlaceholder: 'அல்லது இங்கே பெயர் உள்ளிடு...',
    sortBy: 'வரிசை',
    sortName: 'பெயர்',
    sortQty: 'அளவு',
    sortStatus: 'நிலை',
    searchPlaceholder: 'தேடு...',
    statsTotal: 'மொத்த பொருட்கள்',
    statsLow: 'குறைந்த இருப்பு',
    statsOut: 'வாங்க வேண்டியவை',
    minQtyLabel: 'குறைந்தபட்சம்',
    editItem: 'திருத்து',
    saveEdit: 'சேமி',
    cancel: 'ரத்து செய்',
  },
  te: {
    appTitle: 'స్మార్ట్ సర్వ్',
    appSub: 'ఇంటి వస్తువులు',
    inventory: 'నిల్వలు',
    shoppingList: 'కొనుగోలు',
    addItemPlaceholder: 'వస్తువు పేరు రాయండి...',
    qtyLabel: 'పరిమాణం',
    inventoryEmpty: 'వస్తువులు లేవు. పైన జోడించండి!',
    shoppingEmpty: 'అన్నీ నిండాయి!',
    selectLanguage: 'భాష ఎంచుకోండి',
    shareWhatsApp: 'WhatsApp లో పంపు',
    clearAll: 'అన్నీ తొలగించు',
    restock: 'మళ్ళీ నింపు',
    inStock: 'నిల్వ ఉంది',
    lowStock: 'తక్కువగా ఉంది',
    outOfStock: 'అయిపోయింది',
    needToBuy: 'కొనాలి',
    toastAdded: '✓ జోడించారు',
    toastRemoved: '✓ తొలగించారు',
    toastRestocked: '✓ నింపారు!',
    toastCleared: '✓ జాబితా తొలగించారు',
    toastAutoCart: '🛒 కొనుగోలు జాబితాకు జోడించారు',
    scanBtn: 'స్కాన్',
    voiceBtn: 'వాయిస్',
    scanTitle: 'వస్తువు స్కాన్',
    scanSub: 'కెమెరాను వస్తువు లేదా బార్‌కోడ్‌పై పెట్టండి',
    scanClose: 'మూసివేయి',
    scanDetecting: 'గుర్తిస్తోంది...',
    scanFound: 'కనుగొన్నది: ',
    addToInventory: 'జోడించు',
    scanManualPlaceholder: 'లేదా ఇక్కడ పేరు రాయండి...',
    sortBy: 'క్రమం',
    sortName: 'పేరు',
    sortQty: 'పరిమాణం',
    sortStatus: 'స్థితి',
    searchPlaceholder: 'వెతుకు...',
    statsTotal: 'మొత్తం వస్తువులు',
    statsLow: 'తక్కువ నిల్వ',
    statsOut: 'కొనాల్సినవి',
    minQtyLabel: 'కనిష్టం',
    editItem: 'మార్చు',
    saveEdit: 'సేవ్ చేయి',
    cancel: 'రద్దు చేయి',
  },
  kn: {
    appTitle: 'ಸ್ಮಾರ್ಟ್ ಸರ್ವ್',
    appSub: 'ಮನೆ ಸಾಮಾನು',
    inventory: 'ದಾಸ್ತಾನು',
    shoppingList: 'ಖರೀದಿ',
    addItemPlaceholder: 'ವಸ್ತುವಿನ ಹೆಸರು ಬರೆಯಿರಿ...',
    qtyLabel: 'ಪ್ರಮಾಣ',
    inventoryEmpty: 'ಯಾವ ವಸ್ತುಗಳಿಲ್ಲ. ಮೇಲೆ ಸೇರಿಸಿ!',
    shoppingEmpty: 'ಎಲ್ಲವೂ ತುಂಬಿದೆ!',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆ ಮಾಡಿ',
    shareWhatsApp: 'WhatsApp ನಲ್ಲಿ ಹಂಚಿ',
    clearAll: 'ಎಲ್ಲ ತೆಗೆ',
    restock: 'ಮರು ತುಂಬಿ',
    inStock: 'ಸ್ಟಾಕ್ ಇದೆ',
    lowStock: 'ಕಡಿಮೆ ಇದೆ',
    outOfStock: 'ಮುಗಿದಿದೆ',
    needToBuy: 'ಕೊಳ್ಳಬೇಕು',
    toastAdded: '✓ ಸೇರಿಸಲಾಯಿತು',
    toastRemoved: '✓ ತೆಗೆಯಲಾಯಿತು',
    toastRestocked: '✓ ಮರು ತುಂಬಲಾಯಿತು!',
    toastCleared: '✓ ಪಟ್ಟಿ ತೆರವು',
    toastAutoCart: '🛒 ಖರೀದಿ ಪಟ್ಟಿಗೆ ಸೇರಿಸಲಾಯಿತು',
    scanBtn: 'ಸ್ಕ್ಯಾನ್',
    voiceBtn: 'ಧ್ವನಿ',
    scanTitle: 'ವಸ್ತು ಸ್ಕ್ಯಾನ್',
    scanSub: 'ಕ್ಯಾಮೆರಾವನ್ನು ವಸ್ತು ಅಥವಾ ಬಾರ್‌ಕೋಡ್‌ಗೆ ತೋರಿಸಿ',
    scanClose: 'ಮುಚ್ಚಿ',
    scanDetecting: 'ಗುರುತಿಸುತ್ತಿದೆ...',
    scanFound: 'ಕಂಡುಹಿಡಿದಿದೆ: ',
    addToInventory: 'ಸೇರಿಸಿ',
    scanManualPlaceholder: 'ಅಥವಾ ಇಲ್ಲಿ ಹೆಸರು ಬರೆಯಿರಿ...',
    sortBy: 'ಕ್ರಮ',
    sortName: 'ಹೆಸರು',
    sortQty: 'ಪ್ರಮಾಣ',
    sortStatus: 'ಸ್ಥಿತಿ',
    searchPlaceholder: 'ಹುಡುಕಿ...',
    statsTotal: 'ಒಟ್ಟು ವಸ್ತುಗಳು',
    statsLow: 'ಕಡಿಮೆ ಸ್ಟಾಕ್',
    statsOut: 'ಕೊಳ್ಳಬೇಕಾದವು',
    minQtyLabel: 'ಕನಿಷ್ಠ',
    editItem: 'ಬದಲಾಯಿಸಿ',
    saveEdit: 'ಉಳಿಸಿ',
    cancel: 'ರದ್ದು ಮಾಡಿ',
  },
  ml: {
    appTitle: 'സ്മാർട്ട് സർവ്',
    appSub: 'വീട്ടുസാധനങ്ങൾ',
    inventory: 'സ്റ്റോക്ക്',
    shoppingList: 'ഷോപ്പിംഗ്',
    addItemPlaceholder: 'സാധനത്തിന്റെ പേര് ടൈപ്പ് ചെയ്യൂ...',
    qtyLabel: 'അളവ്',
    inventoryEmpty: 'ഒന്നും ഇല്ല. മുകളിൽ ചേർക്കുക!',
    shoppingEmpty: 'എല്ലാം നിറഞ്ഞു!',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    shareWhatsApp: 'WhatsApp-ൽ പങ്കിടുക',
    clearAll: 'എല്ലാം മായ്ക്കുക',
    restock: 'വീണ്ടും ചേർക്കുക',
    inStock: 'ലഭ്യമാണ്',
    lowStock: 'കുറവാണ്',
    outOfStock: 'തീർന്നു',
    needToBuy: 'വാങ്ങണം',
    toastAdded: '✓ ചേർത്തു',
    toastRemoved: '✓ നീക്കി',
    toastRestocked: '✓ വീണ്ടും ചേർത്തു!',
    toastCleared: '✓ ലിസ്റ്റ് മായ്ച്ചു',
    toastAutoCart: '🛒 ഷോപ്പിംഗ് ലിസ്റ്റിൽ ചേർത്തു',
    scanBtn: 'സ്കാൻ',
    voiceBtn: 'ശബ്ദം',
    scanTitle: 'സാധനം സ്കാൻ',
    scanSub: 'ക്യാമറ സാധനത്തിലേക്ക് ചൂണ്ടുക',
    scanClose: 'അടയ്ക്കൂ',
    scanDetecting: 'തിരിച്ചറിയുന്നു...',
    scanFound: 'കിട്ടി: ',
    addToInventory: 'ചേർക്കൂ',
    scanManualPlaceholder: 'അല്ലെങ്കിൽ ഇവിടെ പേര് ടൈപ്പ് ചെയ്യൂ...',
    sortBy: 'ക്രമം',
    sortName: 'പേര്',
    sortQty: 'അളവ്',
    sortStatus: 'നില',
    searchPlaceholder: 'തിരയൂ...',
    statsTotal: 'ആകെ സാധനങ്ങൾ',
    statsLow: 'കുറഞ്ഞ സ്റ്റോക്ക്',
    statsOut: 'വാങ്ങേണ്ടവ',
    minQtyLabel: 'കുറഞ്ഞത്',
    editItem: 'തിരുത്തൂ',
    saveEdit: 'സേവ് ചെയ്യൂ',
    cancel: 'റദ്ദാക്കൂ',
  },
  mr: {
    appTitle: 'स्मार्ट सर्व',
    appSub: 'घरचे सामान',
    inventory: 'साठा',
    shoppingList: 'खरेदी',
    addItemPlaceholder: 'वस्तूचे नाव लिहा...',
    qtyLabel: 'प्रमाण',
    inventoryEmpty: 'कोणत्याही वस्तू नाहीत. वर जोडा!',
    shoppingEmpty: 'सर्व काही भरलेले आहे!',
    selectLanguage: 'भाषा निवडा',
    shareWhatsApp: 'WhatsApp वर शेअर करा',
    clearAll: 'सर्व हटवा',
    restock: 'परत आणा',
    inStock: 'उपलब्ध',
    lowStock: 'कमी',
    outOfStock: 'संपले',
    needToBuy: 'विकत घ्यायचे',
    toastAdded: '✓ जोडले',
    toastRemoved: '✓ हटवले',
    toastRestocked: '✓ परत आणले!',
    toastCleared: '✓ यादी साफ',
    toastAutoCart: '🛒 खरेदी यादीत जोडले',
    scanBtn: 'स्कॅन',
    voiceBtn: 'आवाज',
    scanTitle: 'वस्तू स्कॅन',
    scanSub: 'कॅमेरा वस्तू किंवा बारकोडवर ठेवा',
    scanClose: 'बंद करा',
    scanDetecting: 'ओळखत आहे...',
    scanFound: 'मिळाले: ',
    addToInventory: 'जोडा',
    scanManualPlaceholder: 'किंवा इथे नाव लिहा...',
    sortBy: 'क्रम',
    sortName: 'नाव',
    sortQty: 'प्रमाण',
    sortStatus: 'स्थिती',
    searchPlaceholder: 'शोधा...',
    statsTotal: 'एकूण वस्तू',
    statsLow: 'कमी साठा',
    statsOut: 'खरेदी करायचे',
    minQtyLabel: 'किमान',
    editItem: 'बदला',
    saveEdit: 'सेव्ह करा',
    cancel: 'रद्द करा',
  },
  gu: {
    appTitle: 'સ્માર્ટ સર્વ',
    appSub: 'ઘરનો સામાન',
    inventory: 'ભંડાર',
    shoppingList: 'ખરીદી',
    addItemPlaceholder: 'વસ્તુનું નામ લખો...',
    qtyLabel: 'જથ્થો',
    inventoryEmpty: 'કોઈ વસ્તુ નથી. ઉપર ઉમેરો!',
    shoppingEmpty: 'બધું ભરેલું છે!',
    selectLanguage: 'ભાષા પસંદ કરો',
    shareWhatsApp: 'WhatsApp પર મોકલો',
    clearAll: 'બધું ભૂંસો',
    restock: 'પાછું ભરો',
    inStock: 'ઉપલબ્ધ',
    lowStock: 'ઓછું',
    outOfStock: 'ખતમ',
    needToBuy: 'ખરીદવાનું',
    toastAdded: '✓ ઉમેર્યું',
    toastRemoved: '✓ હટાવ્યું',
    toastRestocked: '✓ પાછું ભર્યું!',
    toastCleared: '✓ યાદી સાફ',
    toastAutoCart: '🛒 ખરીદી યાદીમાં ઉમેર્યું',
    scanBtn: 'સ્કેન',
    voiceBtn: 'અવાજ',
    scanTitle: 'વસ્તુ સ્કેન',
    scanSub: 'કૅમેરાને વસ્તુ અથવા બારકોડ પર લઈ જાઓ',
    scanClose: 'બંધ કરો',
    scanDetecting: 'ઓળખી રહ્યો છે...',
    scanFound: 'મળ્યું: ',
    addToInventory: 'ઉમેરો',
    scanManualPlaceholder: 'અથવા અહીં નામ લખો...',
    sortBy: 'ક્રમ',
    sortName: 'નામ',
    sortQty: 'જથ્થો',
    sortStatus: 'સ્થિતિ',
    searchPlaceholder: 'શોધો...',
    statsTotal: 'કુલ વસ્તુઓ',
    statsLow: 'ઓછો સ્ટૉક',
    statsOut: 'ખરીદવાની',
    minQtyLabel: 'ન્યૂનતમ',
    editItem: 'બદલો',
    saveEdit: 'સેવ કરો',
    cancel: 'રદ કરો',
  },
  bn: {
    appTitle: 'স্মার্ট সার্ভ',
    appSub: 'ঘরের জিনিসপত্র',
    inventory: 'মজুদ',
    shoppingList: 'কেনাকাটা',
    addItemPlaceholder: 'জিনিসের নাম লিখুন...',
    qtyLabel: 'পরিমাণ',
    inventoryEmpty: 'কোনো জিনিস নেই। উপরে যোগ করুন!',
    shoppingEmpty: 'সব ভর্তি আছে!',
    selectLanguage: 'ভাষা বেছে নিন',
    shareWhatsApp: 'WhatsApp-এ শেয়ার করুন',
    clearAll: 'সব মুছুন',
    restock: 'আবার আনুন',
    inStock: 'মজুদ আছে',
    lowStock: 'কম আছে',
    outOfStock: 'শেষ',
    needToBuy: 'কিনতে হবে',
    toastAdded: '✓ যোগ হয়েছে',
    toastRemoved: '✓ মুছে গেছে',
    toastRestocked: '✓ আবার এসেছে!',
    toastCleared: '✓ তালিকা মুছেছে',
    toastAutoCart: '🛒 কেনাকাটার তালিকায় যোগ হয়েছে',
    scanBtn: 'স্ক্যান',
    voiceBtn: 'কণ্ঠ',
    scanTitle: 'জিনিস স্ক্যান',
    scanSub: 'ক্যামেরা জিনিস বা বারকোডে নির্দেশ করুন',
    scanClose: 'বন্ধ করুন',
    scanDetecting: 'সনাক্ত করছে...',
    scanFound: 'পাওয়া গেছে: ',
    addToInventory: 'যোগ করুন',
    scanManualPlaceholder: 'অথবা এখানে নাম লিখুন...',
    sortBy: 'ক্রম',
    sortName: 'নাম',
    sortQty: 'পরিমাণ',
    sortStatus: 'অবস্থা',
    searchPlaceholder: 'খুঁজুন...',
    statsTotal: 'মোট জিনিস',
    statsLow: 'কম মজুদ',
    statsOut: 'কিনতে হবে',
    minQtyLabel: 'সর্বনিম্ন',
    editItem: 'পরিবর্তন করুন',
    saveEdit: 'সেভ করুন',
    cancel: 'বাতিল করুন',
  },
  or: {
    appTitle: 'ସ୍ମାର୍ଟ ସର୍ଭ',
    appSub: 'ଘରର ସାମଗ୍ରୀ',
    inventory: 'ଭଣ୍ଡାର',
    shoppingList: 'କିଣାକିଣି',
    addItemPlaceholder: 'ଜିନିଷ ନାଁ ଲେଖ...',
    qtyLabel: 'ପରିମାଣ',
    inventoryEmpty: 'କୌଣସି ଜିନିଷ ନାହିଁ। ଉପରେ ଯୋଡ଼ନ୍ତୁ!',
    shoppingEmpty: 'ସବୁ ଭରିଛି!',
    selectLanguage: 'ଭାଷା ବାଛନ୍ତୁ',
    shareWhatsApp: 'WhatsApp ରେ ଶେୟାର',
    clearAll: 'ସବୁ ଡିଲିଟ',
    restock: 'ଫେରାଇ ଆଣ',
    inStock: 'ଉପଲବ୍ଧ',
    lowStock: 'କମ ଅଛି',
    outOfStock: 'ଶେଷ',
    needToBuy: 'କିଣିବା ଦରକାର',
    toastAdded: '✓ ଯୋଡ଼ା ହେଲା',
    toastRemoved: '✓ ହଟାଗଲା',
    toastRestocked: '✓ ଫେରିଆଲା!',
    toastCleared: '✓ ତାଲିକା ସଫା',
    toastAutoCart: '🛒 କିଣାକିଣି ତାଲିକାରେ ଯୋଡ଼ଗଲା',
    scanBtn: 'ସ୍କ୍ୟାନ',
    voiceBtn: 'ଆବାଜ',
    scanTitle: 'ଜିନିଷ ସ୍କ୍ୟାନ',
    scanSub: 'କ୍ୟାମେରା ଜିନିଷ ବା ବାର୍‌କୋଡ ଦିଗରେ ଦେଖା',
    scanClose: 'ବନ୍ଦ କର',
    scanDetecting: 'ଚିହ୍ନଟ ହେଉଛି...',
    scanFound: 'ମିଳିଲା: ',
    addToInventory: 'ଯୋଡ଼ ଦିଅ',
    scanManualPlaceholder: 'ବା ଏଠାରେ ନାଁ ଲେଖ...',
    sortBy: 'କ୍ରମ',
    sortName: 'ନାଁ',
    sortQty: 'ପରିମାଣ',
    sortStatus: 'ସ୍ଥିତି',
    searchPlaceholder: 'ଖୋଜ...',
    statsTotal: 'ମୋଟ ଜିନିଷ',
    statsLow: 'କମ ଷ୍ଟକ',
    statsOut: 'କିଣିବାକୁ ଅଛି',
    minQtyLabel: 'ସର୍ବନିମ୍ନ',
    editItem: 'ବଦଳ',
    saveEdit: 'ସେଭ କର',
    cancel: 'ବାତିଲ',
  },
};

// ── Core state ──────────────────────────────────────────────────────────────
let currentLang = localStorage.getItem('ss_lang') || 'hi';

function t(key) {
  return (TRANSLATIONS[currentLang] && TRANSLATIONS[currentLang][key])
    || TRANSLATIONS['en'][key]
    || key;
}

function setLanguage(code) {
  currentLang = code;
  localStorage.setItem('ss_lang', code);
  applyTranslations();
}

// ── applyTranslations — FIX: handles textContent AND placeholders correctly ─
function applyTranslations() {
  // 1. Static text nodes
  document.querySelectorAll('[data-i18n]').forEach(el => {
    // Don't overwrite buttons that have data-name attribute (scan add btn)
    if (el.id === 'scanAddBtn') return;
    el.textContent = t(el.dataset.i18n);
  });

  // 2. Placeholder attributes
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    el.placeholder = t(el.dataset.i18nPlaceholder);
  });

  // 3. Update language label in header
  const lang = LANGUAGES.find(l => l.code === currentLang);
  if (lang) {
    const lbl = document.getElementById('langLabel');
    if (lbl) lbl.textContent = lang.nativeLabel;
  }

  // 4. Update html lang attribute for accessibility
  document.documentElement.lang = currentLang;
}